title: Stackbit Starter Theme
baseURL: /
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
params:
  description: lorem-ipsum
  header:
    title: lorem-ipsum
    has_nav: true
    nav_links: []
    type: header
  footer:
    has_nav: true
    nav_links: []
    has_social: true
    social_links: []
    content: lorem-ipsum
    links: []
    type: footer
